# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "thefurcel-dropshipping"
client_id = "your_client_id_here"
application_url = "https://your-app.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,write_orders,read_orders,write_fulfillments,read_fulfillments,read_inventory,write_inventory,read_customers"

[auth]
redirect_urls = [
  "https://your-app.com/auth/callback",
  "https://your-app.com/auth/shopify/callback"
]

[webhooks]
api_version = "2024-01"

  [webhooks.subscriptions]
  orders_create = "https://your-app.com/api/webhooks/orders/create"
  fulfillments_create = "https://your-app.com/api/webhooks/fulfillments/create"
  inventory_levels_update = "https://your-app.com/api/webhooks/inventory/update"

[pos]
embedded = false

[app_proxy]
url = "https://your-app.com/api/proxy"
subpath = "apps"
subpath_prefix = "thefurcel"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "your-dev-store.myshopify.com"
